"""Composable Differential Evolution optimizer."""

from .benchmarks import (
    ackley_function,
    beale_function,
    booth_function,
    bukin_function,
    easom_function,
    eggholder_function,
    goldstein_price_function,
    himmelblau_function,
    levi_function,
    mccormick_function,
    matyas_function,
    rastrigin_function,
    schaffer_n2_function,
    sphere_function,
    three_hump_camel_function,
)
from .boundaries import (
    ClipBoundaryHandler,
    NoBoundaryHandler,
    RandomResetBoundaryHandler,
    MidpointBoundaryHandler,
    ReflectionBoundaryHandler,
)
from .crossovers import BinomialCrossover, ExponentialCrossover, IdentityCrossover
from .crossover_rates import AdaptiveCrossoverRate, ConstantCrossoverRate
from .initializers import (
    OppositionInitializer,
    QuasiOppositionInitializer,
    RandomInitializer,
    SobolInitializer,
    TentInitializer,
)
from .diversity import (
    AggregatedDistribution,
    AverageDistanceAroundAllIndividuals,
    AverageDistanceAroundPopulationCenter,
    AveragePairwiseDistance,
    DimensionalVariance,
    PopulationCoherence,
    PopulationDiameter,
    PopulationRadius,
)
from .jde import JDEComponents, jde_rand_1_bin
from .mutation import (
    Best1,
    Best2,
    CurrentToBest1,
    CurrentToBest2,
    CurrentToRand1,
    CurrentToRand2,
    DirectedMutation,
    MutationContext,
    NeighborhoodSearchMutation,
    Rand1,
    Rand2,
    TrigonometricMutation,
    sample_distinct_indices,
)
from .optimizer import DifferentialEvolution
from .population_schedules import (
    HyperbolicTangentPopulationReduction,
    LinearPopulationReduction,
)
from .result import OptimizeResult
from .scales import AdaptiveScaleFactor, ConstantScaleFactor, RandomizedScaleFactor
from .shade import LSHADE, SHADE

__all__ = [
    "LSHADE",
    "SHADE",
    "AdaptiveCrossoverRate",
    "AdaptiveScaleFactor",
    "AggregatedDistribution",
    "AverageDistanceAroundAllIndividuals",
    "AverageDistanceAroundPopulationCenter",
    "AveragePairwiseDistance",
    "Best1",
    "Best2",
    "BinomialCrossover",
    "ClipBoundaryHandler",
    "ConstantCrossoverRate",
    "ConstantScaleFactor",
    "CurrentToBest1",
    "CurrentToBest2",
    "CurrentToRand1",
    "CurrentToRand2",
    "DifferentialEvolution",
    "DimensionalVariance",
    "DirectedMutation",
    "ExponentialCrossover",
    "HyperbolicTangentPopulationReduction",
    "IdentityCrossover",
    "JDEComponents",
    "LinearPopulationReduction",
    "MidpointBoundaryHandler",
    "MutationContext",
    "NeighborhoodSearchMutation",
    "NoBoundaryHandler",
    "OppositionInitializer",
    "OptimizeResult",
    "PopulationCoherence",
    "PopulationDiameter",
    "PopulationRadius",
    "QuasiOppositionInitializer",
    "Rand1",
    "Rand2",
    "RandomInitializer",
    "RandomResetBoundaryHandler",
    "RandomizedScaleFactor",
    "ReflectionBoundaryHandler",
    "SobolInitializer",
    "TentInitializer",
    "TrigonometricMutation",
    "ackley_function",
    "beale_function",
    "booth_function",
    "bukin_function",
    "easom_function",
    "eggholder_function",
    "goldstein_price_function",
    "himmelblau_function",
    "jde_rand_1_bin",
    "levi_function",
    "matyas_function",
    "mccormick_function",
    "rastrigin_function",
    "sample_distinct_indices",
    "schaffer_n2_function",
    "sphere_function",
    "three_hump_camel_function",
]
